# Generated by Django 3.2.8 on 2021-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='doctor.png', upload_to='DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='patient.jpg', upload_to='PatientProfilePic/'),
        ),
    ]
